const PROVIDERS = {
  "Oracle Object Storage":[["path","Path",1,"s3a://bucket/folder"],["endpoint","Storage End Point",1],["key","Storage Key",1,"",1],["secret","Storage Secret",1,"",1]],
  "Secure FTP":[["server","SFTP server name",1,"user@host"],["authenticationKey","Authentication key",1,"",0,1],["folder","Folder name",1]],
  "AWS":[["path","Bucket path",1,"s3://bucket/folder"],["region","Region",1],["accessKey","Access key",1,"",1],["secretKey","Secret key",1,"",1]],
  "Google Cloud Storage":[["path","Bucket path",1,"s3a://bucket/folder"],["endpoint","Storage End Point",1,"storage.googleapis.com"],["key","Storage Key",1,"",1],["secret","Storage Secret",1,"",1]],
  "Salesforce CRM":[["instanceUrl","Instance URL",1,"https://your-org.my.salesforce.com"],["clientId","Client ID",1],["clientSecret","Client Secret",1,"",1],["securityToken","Security Token",0,"",1],["username","Username",1],["password","Password",1,"",1]],
  "CX Sales":[["serviceUrl","Service URL",1],["username","Username",1],["password","Password",1,"",1]]
};
const $=id=>document.getElementById(id), profileType=$("profileType"), profileForm=$("profileForm"), templateForm=$("templateForm");
let profiles=[],templates=[],editingProfileId=null,editingTemplateId=null;
for(const type of Object.keys(PROVIDERS)) profileType.add(new Option(type,type));
function fieldInput([key,label,required,placeholder,secret,file],value="") { const wrap=document.createElement("label"), input=document.createElement("input");wrap.textContent=label;input.name=`profile.${key}`;input.type=file?"file":secret?"password":"text";input.required=false;input.placeholder=placeholder||"";if(!file)input.value=value||"";wrap.append(input);return wrap; }
function renderProfileFields(values={}){$("profileFields").replaceChildren(...PROVIDERS[profileType.value].map(spec=>fieldInput(spec,values[spec[0]])));}
function profileSummary(p){return p.type;}
function escape(value){const el=document.createElement("div");el.textContent=value||"";return el.innerHTML;}
function exportCatalog(){const usedKeys=new Set(),profileKeys=new Map(),slug=value=>String(value||"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"profile";for(const profile of profiles){let base=slug(profile.name),key=base,index=2;while(usedKeys.has(key))key=`${base}-${index++}`;usedKeys.add(key);profileKeys.set(profile.id,key);}const catalog={profiles:profiles.map(profile=>({key:profileKeys.get(profile.id),name:profile.name,type:profile.type,fields:profile.fields||{}})),templates:templates.map(template=>({id:template.id,name:template.name,description:template.description||"",sourceProfileKey:profileKeys.get(template.source?.profileId),destinationProfileKey:profileKeys.get(template.destination?.profileId),fileContract:template.fileContract||{}}))},text=JSON.stringify(catalog,null,2),url=URL.createObjectURL(new Blob([text],{type:"application/json"})),link=document.createElement("a");link.href=url;link.download=`cdp-transfer-catalog-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
function renderProfiles(){const list=$("profileList");list.replaceChildren(...profiles.map(p=>{const card=document.createElement("article");card.className="template";const copy=document.createElement("div");copy.innerHTML=`<strong>${escape(p.name)}</strong><p>${escape(profileSummary(p))}</p>`;const edit=document.createElement("button");edit.className="text";edit.textContent="Edit";edit.onclick=()=>openProfile(p,card);card.append(copy,edit);return card;}));renderProfileSelects();}
function renderProfileSelects(){for(const [id,side] of [["sourceProfile","source"],["destinationProfile","destination"]]){const select=$(id),current=select.value;select.replaceChildren(new Option(`Select ${side} profile`,""),...profiles.map(p=>new Option(`${p.name} — ${p.type}`,p.id)));select.value=current;}}
function renderTemplates(){const list=$("templateList");list.replaceChildren(...templates.map(t=>{const source=profiles.find(p=>p.id===t.source?.profileId),dest=profiles.find(p=>p.id===t.destination?.profileId);const card=document.createElement("article");card.className="template";const copy=document.createElement("div");copy.innerHTML=`<strong>${escape(t.name)}</strong><p>${escape(source?.name||t.source?.type)} → ${escape(dest?.name||t.destination?.type)} · ${escape(t.fileContract?.format||"CSV")} · ${escape(t.fileContract?.compression||"none")}</p>`;const edit=document.createElement("button");edit.className="text";edit.textContent="Edit";edit.onclick=()=>openTemplate(t,card);card.append(copy,edit);return card;}));}
function fileData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});}
function clearInlineEditors(){document.querySelectorAll(".template.is-editing").forEach(card=>card.classList.remove("is-editing"));}
function closeInlineEditor(form){form.hidden=true;form.classList.remove("inline-editor");form.removeAttribute("data-editor");clearInlineEditors();}
function openProfile(profile,anchor){editingProfileId=profile?.id||null;clearInlineEditors();profileForm.classList.toggle("inline-editor",Boolean(anchor));if(anchor){anchor.classList.add("is-editing");profileForm.dataset.editor="Editing connection profile";anchor.after(profileForm);}else{profileForm.removeAttribute("data-editor");$("profileList").after(profileForm);}profileForm.hidden=false;profileForm.reset();$("profileFormTitle").textContent=profile?"Edit connection profile":"New connection profile";profileType.value=profile?.type||"Oracle Object Storage";profileForm.elements.profileName.value=profile?.name||"";renderProfileFields(profile?.fields||{});$("deleteProfileBtn").hidden=!profile;}
async function saveProfile(event){event.preventDefault();const old=profiles.find(p=>p.id===editingProfileId), type=profileType.value, fields={};for(const [key,, , , ,file] of PROVIDERS[type]){const input=profileForm.elements[`profile.${key}`];fields[key]=file?(input.files[0]?{fileName:input.files[0].name,data:await fileData(input.files[0])}:old?.fields?.[key]||""):input.value.trim();}const profile={id:old?.id||crypto.randomUUID(),name:profileForm.elements.profileName.value.trim(),type,fields};if(!profile.name){$("profileMessage").textContent="Enter a profile name.";return;}profiles=old?profiles.map(p=>p.id===old.id?profile:p):[...profiles,profile];try{const result=await chrome.runtime.sendMessage({type:"connection-profile-save",profiles});if(result?.ok){profileForm.hidden=true;renderProfiles();renderTemplates();}else $("profileMessage").textContent=result?.error||"Could not save.";}catch(error){$("profileMessage").textContent=`Could not save: ${error.message||error}`;}}
function applyContract(template={}){const contract=template.fileContract||{};for(const key of ["format","filePatternMode","filePattern","charset","csvParser","delimiter","destinationFileName","dateFormat","compression","decryptionPassphrase"]){if(templateForm.elements[key]&&contract[key]!==undefined)templateForm.elements[key].value=contract[key];}$("regexWrap").hidden=templateForm.elements.filePatternMode.value!=="regex";}
function openTemplate(template,anchor){editingTemplateId=template?.id||null;clearInlineEditors();templateForm.classList.toggle("inline-editor",Boolean(anchor));if(anchor){anchor.classList.add("is-editing");templateForm.dataset.editor="Editing transfer template";anchor.after(templateForm);}else{templateForm.removeAttribute("data-editor");$("templateList").after(templateForm);}templateForm.hidden=false;templateForm.reset();$("formTitle").textContent=template?"Edit transfer template":"New transfer template";renderProfileSelects();$("sourceProfile").value=template?.source?.profileId||"";$("destinationProfile").value=template?.destination?.profileId||"";templateForm.elements.name.value=template?.name||"";templateForm.elements.description.value=template?.description||"";applyContract(template);$("deleteTemplateBtn").hidden=!template;}
async function saveTemplate(event){event.preventDefault();const old=templates.find(t=>t.id===editingTemplateId), source=profiles.find(p=>p.id===$("sourceProfile").value), destination=profiles.find(p=>p.id===$("destinationProfile").value);if(!source||!destination){$("formMessage").textContent="Select both a Source and Destination profile.";return;}const data=new FormData(templateForm), contract={format:data.get("format"),filePatternMode:data.get("filePatternMode"),filePattern:data.get("filePattern"),charset:data.get("charset"),csvParser:data.get("csvParser"),delimiter:data.get("delimiter"),destinationFileName:data.get("destinationFileName"),dateFormat:data.get("dateFormat"),compression:data.get("compression"),decryptionPassphrase:data.get("decryptionPassphrase")};for(const key of ["encryptionFile","decryptionFile"]){const input=templateForm.elements[key];contract[key]=input.files[0]?{fileName:input.files[0].name,data:await fileData(input.files[0])}:old?.fileContract?.[key]||"";}if(contract.compression==="gzip"&&contract.filePatternMode==="automatic")contract.filePattern=`^${contract.destinationFileName||"PROFILE_.*"}.*\\.gz$`;const next={id:old?.id||crypto.randomUUID(),name:data.get("name").trim(),description:data.get("description").trim(),source:{profileId:source.id,type:source.type},destination:{profileId:destination.id,type:destination.type},fileContract:contract};if(!next.name)return;templates=old?templates.map(t=>t.id===old.id?next:t):[...templates,next];const result=await chrome.runtime.sendMessage({type:"template-save",templates});if(result.ok){templateForm.hidden=true;renderTemplates();}else $("formMessage").textContent=result.error||"Could not save.";}
async function refresh(){const [templateResult,profileResult]=await Promise.all([chrome.runtime.sendMessage({type:"template-list-private"}),chrome.runtime.sendMessage({type:"connection-profile-list"})]);templates=templateResult.templates||[];profiles=profileResult.profiles||[];$("vaultState").textContent="Local";renderProfiles();renderTemplates();}
profileType.onchange=()=>renderProfileFields();$("exportCatalogBtn").onclick=exportCatalog;$("newProfileBtn").onclick=()=>openProfile();$("cancelProfileBtn").onclick=()=>closeInlineEditor(profileForm);$("deleteProfileBtn").onclick=async()=>{if(!confirm("Delete this connection profile?"))return;profiles=profiles.filter(p=>p.id!==editingProfileId);const result=await chrome.runtime.sendMessage({type:"connection-profile-save",profiles});if(result.ok){closeInlineEditor(profileForm);renderProfiles();renderTemplates();}};profileForm.onsubmit=saveProfile;
$("newTemplateBtn").onclick=()=>openTemplate();$("cancelTemplateBtn").onclick=()=>closeInlineEditor(templateForm);$("deleteTemplateBtn").onclick=async()=>{if(!confirm("Delete this template?"))return;templates=templates.filter(t=>t.id!==editingTemplateId);const result=await chrome.runtime.sendMessage({type:"template-save",templates});if(result.ok){closeInlineEditor(templateForm);renderTemplates();}};templateForm.elements.filePatternMode.onchange=()=>$("regexWrap").hidden=templateForm.elements.filePatternMode.value!=="regex";templateForm.onsubmit=saveTemplate;
refresh();
