const PROVIDERS = {
  "Oracle Object Storage":[["path","Path",1,"s3a://bucket/folder"],["endpoint","Storage End Point",1],["key","Storage Key",1,"",1],["secret","Storage Secret",1,"",1]],
  "Secure FTP":[["server","SFTP server name",1,"user@host"],["authenticationKey","Authentication key",1,"",0,1],["folder","Folder name",1]],
  "AWS":[["path","Bucket path",1,"s3://bucket/folder"],["endpoint","Storage End Point",1,"s3_bucket.region.your_s3_endpoint"],["accessKey","Storage Key",1,"",1],["secretKey","Storage Secret",1,"",1]],
  "Google Cloud Storage":[["path","Bucket path",1,"s3a://bucket/folder"],["endpoint","Storage End Point",1,"storage.googleapis.com"],["key","Storage Key",1,"",1],["secret","Storage Secret",1,"",1]],
  "Salesforce CRM":[["instanceUrl","Instance URL",1,"https://your-org.my.salesforce.com"],["clientId","Client ID",1],["clientSecret","Client Secret",1,"",1],["securityToken","Security Token",0,"",1],["username","Username",1],["password","Password",1,"",1]],
  "CX Sales":[["serviceUrl","Service URL",1],["username","Username",1],["password","Password",1,"",1]]
};
const $=id=>document.getElementById(id), profileType=$("profileType"), profileForm=$("profileForm"), templateForm=$("templateForm");
let profiles=[],templates=[],editingProfileId=null,editingTemplateId=null;
for(const type of Object.keys(PROVIDERS)) profileType.add(new Option(type,type));
function fieldInput([key,label,required,placeholder,secret,file],value="") { const input=document.createElement("input");input.name=`profile.${key}`;input.required=false;if(file){const wrap=document.createElement("div"),caption=document.createElement("span"),control=document.createElement("div"),picker=document.createElement("label"),selected=document.createElement("span"),id=`profileFile-${key}`;wrap.className="file-field";caption.textContent=label;control.className="file-control";picker.className="file-picker";picker.htmlFor=id;picker.textContent="Choose file";input.id=id;input.type="file";selected.className="file-selected";selected.textContent=value?.fileName||"No file selected";input.onchange=()=>selected.textContent=input.files[0]?.name||value?.fileName||"No file selected";control.append(picker,input,selected);wrap.append(caption,control);return wrap;}const wrap=document.createElement("label");wrap.textContent=label;input.type=secret?"password":"text";input.placeholder=placeholder||"";input.value=value||"";wrap.append(input);return wrap; }
function renderProfileFields(values={}){$("profileFields").replaceChildren(...PROVIDERS[profileType.value].map(spec=>fieldInput(spec,values[spec[0]])));}
const PROVIDER_ORDER=["OOS","SFTP","AWS","GCS","CX Sales","Salesforce"];
function providerGroup(type){return {"Oracle Object Storage":"OOS","Secure FTP":"SFTP","Google Cloud Storage":"GCS","CX Sales":"CX Sales","Salesforce CRM":"Salesforce",AWS:"AWS"}[type]||type||"Other";}
function groupContainer(groups,provider){if(groups.has(provider))return groups.get(provider);const group=document.createElement("section"),title=document.createElement("h3"),items=document.createElement("div");group.className="provider-template-group";title.textContent=provider;items.className="provider-template-items";group.append(title,items);const entry={group,items};groups.set(provider,entry);return entry;}
function orderedGroups(groups){return [...groups.keys()].sort((a,b)=>{const ai=PROVIDER_ORDER.indexOf(a),bi=PROVIDER_ORDER.indexOf(b);return (ai<0?PROVIDER_ORDER.length:ai)-(bi<0?PROVIDER_ORDER.length:bi)||a.localeCompare(b);}).map(name=>groups.get(name).group);}
function escape(value){const el=document.createElement("div");el.textContent=value||"";return el.innerHTML;}
function exportCatalog(){const usedKeys=new Set(),profileKeys=new Map(),slug=value=>String(value||"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"profile";for(const profile of profiles){let base=slug(profile.name),key=base,index=2;while(usedKeys.has(key))key=`${base}-${index++}`;usedKeys.add(key);profileKeys.set(profile.id,key);}const catalog={profiles:profiles.map(profile=>({key:profileKeys.get(profile.id),name:profile.name,type:profile.type,fields:profile.fields||{}})),templates:templates.map(template=>({id:template.id,name:template.name,kind:template.kind||"file",sourceProfileKey:profileKeys.get(template.source?.profileId),destinationProfileKey:profileKeys.get(template.destination?.profileId),...(template.kind==="direct"?{}:{fileContract:template.fileContract||{}})}))},text=JSON.stringify(catalog,null,2),url=URL.createObjectURL(new Blob([text],{type:"application/json"})),link=document.createElement("a");link.href=url;link.download=`cdp-transfer-catalog-${new Date().toISOString().slice(0,10)}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),0);}
function catalogNotice(text){const message=$("catalogMessage");message.textContent=text;message.hidden=!text;}
async function importCatalog(file){try{const catalog=JSON.parse(await file.text()),incomingProfiles=Array.isArray(catalog.profiles)?catalog.profiles:null,incomingTemplates=Array.isArray(catalog.templates)?catalog.templates:null;if(!incomingProfiles||!incomingTemplates)throw new Error("The selected file is not a transfer catalog.");const keyToProfileId=new Map(),nextProfiles=[...profiles];for(const incoming of incomingProfiles){if(!incoming?.key||!incoming.name||!incoming.type)throw new Error("A connection profile is missing its key, name, or type.");const existing=nextProfiles.find(profile=>profile.name===incoming.name&&profile.type===incoming.type),id=existing?.id||crypto.randomUUID(),next={id,name:incoming.name,type:incoming.type,fields:incoming.fields||{}};if(existing)nextProfiles.splice(nextProfiles.indexOf(existing),1,next);else nextProfiles.push(next);keyToProfileId.set(incoming.key,id);}const nextTemplates=[...templates];for(const incoming of incomingTemplates){if(!incoming?.name)throw new Error("A template is missing its name.");const sourceProfileId=keyToProfileId.get(incoming.sourceProfileKey),destinationProfileId=keyToProfileId.get(incoming.destinationProfileKey);if(!sourceProfileId||!destinationProfileId)throw new Error(`Template ${incoming.name} refers to a profile that is not in this catalog.`);const source=nextProfiles.find(profile=>profile.id===sourceProfileId),destination=nextProfiles.find(profile=>profile.id===destinationProfileId),kind=incoming.kind==="direct"?"direct":"file",next={id:incoming.id||crypto.randomUUID(),name:incoming.name,kind,source:{profileId:source.id,type:source.type},destination:{profileId:destination.id,type:destination.type}};if(kind!=="direct")next.fileContract=incoming.fileContract||{};const existing=nextTemplates.find(template=>template.id===next.id||template.name===next.name);if(existing)nextTemplates.splice(nextTemplates.indexOf(existing),1,next);else nextTemplates.push(next);}if(!confirm(`Import ${incomingProfiles.length} connection profile(s) and ${incomingTemplates.length} template(s)? Matching names will be updated.`))return;const profileResult=await chrome.runtime.sendMessage({type:"connection-profile-save",profiles:nextProfiles});if(!profileResult?.ok)throw new Error(profileResult?.error||"Could not import connection profiles.");const templateResult=await chrome.runtime.sendMessage({type:"template-save",templates:nextTemplates});if(!templateResult?.ok)throw new Error(templateResult?.error||"Could not import templates.");profiles=nextProfiles;templates=nextTemplates;renderProfiles();renderTemplates();catalogNotice(`Imported ${incomingProfiles.length} connection profile(s) and ${incomingTemplates.length} template(s).`);}catch(error){catalogNotice(`Import failed: ${error.message||error}`);}}
function renderProfiles(){const list=$("profileList"),groups=new Map();for(const p of profiles){const card=document.createElement("article"),row=document.createElement("button");card.className="template";row.type="button";row.className="template-toggle";row.title=p.name;row.setAttribute("aria-expanded","false");row.innerHTML=`<span><strong>${escape(p.name)}</strong></span>`;row.onclick=()=>{if(!profileForm.hidden&&profileForm.dataset.targetId===p.id){closeInlineEditor(profileForm);editingProfileId=null;renderProfiles();return;}closeInlineEditor(templateForm);closeInlineEditor(profileForm);renderTemplates();openProfile(p,card,row);};card.append(row);groupContainer(groups,providerGroup(p.type)).items.append(card);}list.replaceChildren(...orderedGroups(groups));renderProfileSelects();}
function renderProfileSelects(){for(const [id,side] of [["sourceProfile","source"],["destinationProfile","destination"]]){const select=$(id),current=select.value;select.replaceChildren(new Option(`Select ${side} profile`,""),...profiles.map(p=>new Option(`${p.name} — ${p.type}`,p.id)));select.value=current;}}
function templateProvider(template){return providerGroup(profiles.find(p=>p.id===template.source?.profileId)?.type||template.source?.type);}
function renderTemplates(){const list=$("templateList"),groups=new Map();for(const t of templates){const provider=templateProvider(t),source=profiles.find(p=>p.id===t.source?.profileId),dest=profiles.find(p=>p.id===t.destination?.profileId),card=document.createElement("article"),row=document.createElement("button");card.className="template";row.type="button";row.className="template-toggle";row.title=t.name;row.setAttribute("aria-expanded","false");const summary=t.kind==="direct"?`${escape(source?.name||t.source?.type)} · Direct application`:`${escape(source?.name||t.source?.type)} → ${escape(dest?.name||t.destination?.type)} · ${escape(t.fileContract?.format||"CSV")} · ${escape(t.fileContract?.compression||"none")}`;row.innerHTML=`<span><strong>${escape(t.name)}</strong><p>${summary}</p></span>`;row.onclick=()=>{if(!templateForm.hidden&&templateForm.dataset.targetId===t.id){closeInlineEditor(templateForm);editingTemplateId=null;renderTemplates();return;}closeInlineEditor(profileForm);closeInlineEditor(templateForm);renderProfiles();openTemplate(t,card,row);};card.append(row);groupContainer(groups,provider).items.append(card);}list.replaceChildren(...orderedGroups(groups));}
function fileData(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file);});}
function clearInlineEditors(){document.querySelectorAll(".template.is-editing").forEach(card=>card.classList.remove("is-editing"));}
function closeInlineEditor(form){form.hidden=true;form.classList.remove("inline-editor");form.removeAttribute("data-editor");form.removeAttribute("data-target-id");clearInlineEditors();}
function openProfile(profile,anchor,row){editingProfileId=profile?.id||null;clearInlineEditors();profileForm.classList.toggle("inline-editor",Boolean(anchor));if(anchor){anchor.classList.add("is-editing");row?.setAttribute("aria-expanded","true");profileForm.dataset.editor="Connection profile";}else profileForm.removeAttribute("data-editor");$("connectionsSection").append(profileForm);profileForm.dataset.targetId=profile?.id||"new";profileForm.hidden=false;profileForm.reset();$("profileFormTitle").textContent=profile?"Connection profile":"New connection profile";profileType.value=profile?.type||"Oracle Object Storage";profileForm.elements.profileName.value=profile?.name||"";renderProfileFields(profile?.fields||{});$("deleteProfileBtn").hidden=!profile;}
async function saveProfile(event){event.preventDefault();const old=profiles.find(p=>p.id===editingProfileId), type=profileType.value, fields={};for(const [key,, , , ,file] of PROVIDERS[type]){const input=profileForm.elements[`profile.${key}`];fields[key]=file?(input.files[0]?{fileName:input.files[0].name,data:await fileData(input.files[0])}:old?.fields?.[key]||""):input.value.trim();}const profile={id:old?.id||crypto.randomUUID(),name:profileForm.elements.profileName.value.trim(),type,fields};if(!profile.name){$("profileMessage").textContent="Enter a profile name.";return;}profiles=old?profiles.map(p=>p.id===old.id?profile:p):[...profiles,profile];try{const result=await chrome.runtime.sendMessage({type:"connection-profile-save",profiles});if(result?.ok){profileForm.hidden=true;renderProfiles();renderTemplates();}else $("profileMessage").textContent=result?.error||"Could not save.";}catch(error){$("profileMessage").textContent=`Could not save: ${error.message||error}`;}}
function setFileName(key,file){$(key+"Name").textContent=file?.fileName||"No file selected";}
function setTemplateNameEditable(editable){const input=$("templateName");input.readOnly=!editable;$("editTemplateNameBtn").textContent=editable?"Done":"Edit";if(editable)input.focus();}
function applyContract(template={}){const contract=template.fileContract||{};for(const key of ["format","filePatternMode","filePattern","charset","csvParser","delimiter","destinationFileName","dateFormat","compression","decryptionPassphrase"]){if(templateForm.elements[key]&&contract[key]!==undefined)templateForm.elements[key].value=contract[key];}setFileName("encryptionFile",contract.encryptionFile);setFileName("decryptionFile",contract.decryptionFile);$("regexWrap").hidden=templateForm.elements.filePatternMode.value!=="regex";}
function openTemplate(template,anchor,row){editingTemplateId=template?.id||null;clearInlineEditors();templateForm.classList.toggle("inline-editor",Boolean(anchor));if(anchor){anchor.classList.add("is-editing");row?.setAttribute("aria-expanded","true");templateForm.dataset.editor="Template";$("savedTemplatesSection").append(templateForm);}else{templateForm.removeAttribute("data-editor");$("savedTemplatesSection").append(templateForm);}templateForm.dataset.targetId=template?.id||"new";templateForm.hidden=false;templateForm.reset();const direct=template?.kind==="direct";templateForm.dataset.templateKind=direct?"direct":"file";$("fileContractFields").hidden=direct;renderProfileSelects();$("sourceProfile").value=template?.source?.profileId||"";$("destinationProfile").value=template?.destination?.profileId||"";templateForm.elements.name.value=template?.name||"";setTemplateNameEditable(!template);if(!direct)applyContract(template);else{setFileName("encryptionFile");setFileName("decryptionFile");}$("deleteTemplateBtn").hidden=!template;}
async function saveTemplate(event){event.preventDefault();const old=templates.find(t=>t.id===editingTemplateId), source=profiles.find(p=>p.id===$("sourceProfile").value), destination=profiles.find(p=>p.id===$("destinationProfile").value);if(!source||!destination){$("formMessage").textContent="Select both a Source and Destination profile.";return;}const data=new FormData(templateForm), direct=templateForm.dataset.templateKind==="direct", next={id:old?.id||crypto.randomUUID(),name:data.get("name").trim(),source:{profileId:source.id,type:source.type},destination:{profileId:destination.id,type:destination.type},kind:direct?"direct":"file"};if(!direct){const contract={format:data.get("format"),filePatternMode:data.get("filePatternMode"),filePattern:data.get("filePattern"),charset:data.get("charset"),csvParser:data.get("csvParser"),delimiter:data.get("delimiter"),destinationFileName:data.get("destinationFileName"),dateFormat:data.get("dateFormat"),compression:data.get("compression"),decryptionPassphrase:data.get("decryptionPassphrase")};for(const key of ["encryptionFile","decryptionFile"]){const input=templateForm.elements[key];contract[key]=input.files[0]?{fileName:input.files[0].name,data:await fileData(input.files[0])}:old?.fileContract?.[key]||"";}if(contract.compression==="gzip"&&contract.filePatternMode==="automatic")contract.filePattern=`^${contract.destinationFileName||"PROFILE_.*"}.*\\.gz$`;next.fileContract=contract;}if(!next.name)return;templates=old?templates.map(t=>t.id===old.id?next:t):[...templates,next];const result=await chrome.runtime.sendMessage({type:"template-save",templates});if(result.ok){closeInlineEditor(templateForm);editingTemplateId=null;renderTemplates();}else $("formMessage").textContent=result.error||"Could not save.";}
async function refresh(){const [templateResult,profileResult]=await Promise.all([chrome.runtime.sendMessage({type:"template-list-private"}),chrome.runtime.sendMessage({type:"connection-profile-list"})]);templates=templateResult.templates||[];profiles=profileResult.profiles||[];$("vaultState").textContent="Local";renderProfiles();renderTemplates();}
function selectManagerTab(tab){const connections=tab==="connections";closeInlineEditor(profileForm);closeInlineEditor(templateForm);editingProfileId=null;editingTemplateId=null;$("connectionsSection").hidden=!connections;$("savedTemplatesSection").hidden=connections;$("connectionsTab").setAttribute("aria-selected",String(connections));$("savedTemplatesTab").setAttribute("aria-selected",String(!connections));renderProfiles();renderTemplates();}
profileType.onchange=()=>renderProfileFields();$("exportCatalogBtn").onclick=exportCatalog;$("importCatalogBtn").onclick=()=>$("importCatalogInput").click();$("importCatalogInput").onchange=async(event)=>{const file=event.target.files[0];event.target.value="";if(file)await importCatalog(file);};$("newProfileBtn").onclick=()=>{closeInlineEditor(templateForm);closeInlineEditor(profileForm);renderProfiles();renderTemplates();openProfile();};$("closeProfileBtn").onclick=()=>{closeInlineEditor(profileForm);editingProfileId=null;renderProfiles();};$("deleteProfileBtn").onclick=async()=>{if(!confirm("Delete this connection profile?"))return;profiles=profiles.filter(p=>p.id!==editingProfileId);const result=await chrome.runtime.sendMessage({type:"connection-profile-save",profiles});if(result.ok){closeInlineEditor(profileForm);editingProfileId=null;renderProfiles();renderTemplates();}};profileForm.onsubmit=saveProfile;
$("newTemplateBtn").onclick=()=>{closeInlineEditor(profileForm);closeInlineEditor(templateForm);renderProfiles();renderTemplates();openTemplate();};$("closeTemplateBtn").onclick=()=>{closeInlineEditor(templateForm);editingTemplateId=null;renderTemplates();};$("deleteTemplateBtn").onclick=async()=>{if(!confirm("Delete this template?"))return;templates=templates.filter(t=>t.id!==editingTemplateId);const result=await chrome.runtime.sendMessage({type:"template-save",templates});if(result.ok){closeInlineEditor(templateForm);editingTemplateId=null;renderTemplates();}};$("editTemplateNameBtn").onclick=()=>setTemplateNameEditable($("templateName").readOnly);for(const key of ["encryptionFile","decryptionFile"])templateForm.elements[key].onchange=()=>setFileName(key,templateForm.elements[key].files[0]);templateForm.elements.filePatternMode.onchange=()=>$("regexWrap").hidden=templateForm.elements.filePatternMode.value!=="regex";templateForm.onsubmit=saveTemplate;
$("connectionsTab").onclick=()=>selectManagerTab("connections");$("savedTemplatesTab").onclick=()=>selectManagerTab("templates");
refresh();
